# Consumer engagement

Fig. 1(d). Match user-video interactions on platform-labeled AIGC to unlabeled content. The duration caliper is 3 seconds and is applied after the distance.

### 1. The two arms

Focal is the treated arm. Comparison is the other arm. Nothing is paired yet.

In [1]:
from pathlib import Path
import sys

here = Path.cwd().resolve()
for candidate in [here, *here.parents]:
    if (candidate / "run_pipeline.py").exists():
        sys.path.insert(0, str(candidate))
        root = candidate
        break
else:
    raise FileNotFoundError("Open this notebook from the repository.")

from core.pipeline import ensure_synthetic, load_config

cfg = load_config(root)
spec = cfg["tasks"]["consumer"]
pool = ensure_synthetic(root, cfg, rebuild=False)[{"creator": "creators", "consumer": "consumers", "video": "videos", "algorithm": "algorithm"}["consumer"]]
focal = pool[pool["treated"] == 1].reset_index(drop=True)
comparison = pool[pool["treated"] == 0].reset_index(drop=True)
import pandas as pd
pd.DataFrame([{
    "focal_label": spec["focal"],
    "comparison_label": spec["comparison"],
    "n_focal": len(focal),
    "n_comparison": len(comparison),
    "exact": ", ".join(spec["exact"]),
    "caliper": ", ".join(f"{name} <= {limit}" for name, limit in (spec.get("caliper") or {}).items()) or "none",
}])

             focal_label   comparison_label  n_focal  n_comparison                                             exact                  caliper
0  platform-labeled AIGC  unlabeled content     2400          2400  gender, city, category, time_of_day, upload_week  duration_seconds <= 3.0

### 2. Exact cells

Units are blocked on the categorical covariates first. A focal unit whose cell has no comparison unit cannot be matched, before any distance is computed.

In [2]:
from core.matching import exact_cell_counts

cells = exact_cell_counts(focal, comparison, spec["exact"])
cells.sort_values(["n_comparison", "n_focal"], ascending=[True, False])

     gender   city category time_of_day upload_week  n_focal  n_comparison
62   female  south     food     morning      week_1       12             2
175    male  north  leisure     morning      week_4        5             2
135  female   east   beauty     evening      week_4       13             3
234    male  south   beauty       night      week_1       12             3
160    male  north  leisure        noon      week_2       10             3
11   female  north     food       night      week_4        8             3
151    male  north     food     evening      week_4        8             3
219    male  south  leisure       night      week_4        6             3
179    male  north   beauty        noon      week_4        5             3
33   female  north   beauty        noon      week_3       17             4
206    male  south     food     morning      week_1       11             4
285    male   east   beauty     morning      week_3       11             4
174    male  north  leisure     morning      week_1       10             4
97   female   east     food        noon      week_3        9             4
39   female  north   beauty     evening      week_4        7             4
63   female  south     food     morning      week_4        7             4
89   female  south   beauty       night      week_3        6             4
144    male  north     food        noon      week_2        6             4
164    male  north  leisure     evening      week_2        6             4
46   female  north   beauty     morning      week_1        5             4
81   female  south   beauty        noon      week_3        5             4
222    male  south  leisure     morning      week_1        5             4
251    male   east     food       night      week_4        4             4
242    male   east     food        noon      week_1       14             5
153    male  north     food       night      week_3       13             5
70   female  south  leisure     evening      week_1       12             5
26   female  north  leisure       night      week_1       11             5
170    male  north  leisure       night      week_1       11             5
154    male  north     food       night      week_1       10             5
181    male  north   beauty     evening      week_3       10             5
4    female  north     food     evening      week_2        9             5
79   female  south  leisure     morning      week_4        9             5
101  female   east     food     evening      week_3        9             5
201    male  south     food       night      week_3        9             5
215    male  south  leisure     evening      week_4        9             5
167    male  north  leisure     evening      week_4        8             5
210    male  south  leisure        noon      week_1        8             5
241    male   east     food        noon      week_3        8             5
31   female  north  leisure     morning      week_4        7             5
114  female   east  leisure        noon      week_1        7             5
203    male  south     food       night      week_4        7             5
117  female   east  leisure     evening      week_3        6             5
277    male   east   beauty     evening      week_3        6             5
159    male  north     food     morning      week_4        5             5
258    male   east  leisure        noon      week_1        5             5
273    male   east   beauty        noon      week_3        5             5
136  female   east   beauty       night      week_2        3             5
48   female  south     food        noon      week_2       11             6
105  female   east     food       night      week_3       11             6
118  female   east  leisure     evening      week_1       11             6
261    male   east  leisure     evening      week_3       11             6
29   female  north  leisure     morning      week_3       10             6
115  female   east  leisure        noon      week_4       10             6
155    male  north     food       night      week_4       10             6
1    female  north     food        noon      week_3        9             6
13   female  north     food     morning      week_3        9             6
132  female   east   beauty     evening      week_2        9             6
195    male  south     food        noon      week_4        9             6
196    male  south     food     evening      week_2        9             6
214    male  south  leisure     evening      week_1        9             6
266    male   east  leisure       night      week_1        9             6
44   female  north   beauty     morning      week_2        8             6
157    male  north     food     morning      week_3        8             6
177    male  north   beauty        noon      week_3        8             6
224    male  south   beauty        noon      week_2        8             6
256    male   east  leisure        noon      week_2        8             6
27   female  north  leisure       night      week_4        7             6
45   female  north   beauty     morning      week_3        7             6
149    male  north     food     evening      week_3        7             6
264    male   east  leisure       night      week_2        7             6
227    male  south   beauty        noon      week_4        6             6
76   female  south  leisure     morning      week_2        5             6
281    male   east   beauty       night      week_3        5             6
9    female  north     food       night      week_3        4             6
82   female  south   beauty        noon      week_1        4             6
131  female   east   beauty        noon      week_4        4             6
276    male   east   beauty     evening      week_2        4             6
75   female  south  leisure       night      week_4       17             7
125  female   east  leisure     morning      week_3       13             7
252    male   east     food     morning      week_2       13             7
108  female   east     food     morning      week_2       12             7
213    male  south  leisure     evening      week_3       12             7
282    male   east   beauty       night      week_1       12             7
10   female  north     food       night      week_1       11             7
20   female  north  leisure     evening      week_2       11             7
49   female  south     food        noon      week_3       11             7
66   female  south  leisure        noon      week_1       11             7
107  female   east     food       night      week_4       11             7
178    male  north   beauty        noon      week_1       11             7
127  female   east  leisure     morning      week_4       10             7
191    male  north   beauty     morning      week_4       10             7
262    male   east  leisure     evening      week_1       10             7
263    male   east  leisure     evening      week_4       10             7
274    male   east   beauty        noon      week_1       10             7
56   female  south     food       night      week_2        9             7
186    male  north   beauty       night      week_1        9             7
194    male  south     food        noon      week_1        9             7
200    male  south     food       night      week_2        9             7
209    male  south  leisure        noon      week_3        9             7
236    male  south   beauty     morning      week_2        9             7
250    male   east     food       night      week_1        9             7
255    male   east     food     morning      week_4        9             7
259    male   east  leisure        noon      week_4        9             7
25   female  north  leisure       night      week_3        8             7
30   female  north  leisure     morning      week_1        8             7
40   female  north   beauty       night      week_2        8             7
99   female   east     food        noon      week_4        8             7
104  female   east     food       night      week_2        8             7
238    male  south   beauty     morning      week_1        8             7
239    male  south   beauty     morning      week_4        8             7
257    male   east  leisure        noon      week_3        8             7
269    male   east  leisure     morning      week_3        8             7
69   female  south  leisure     evening      week_3        7             7
72   female  south  leisure       night      week_2        7             7
202    male  south     food       night      week_1        7             7
233    male  south   beauty       night      week_3        7             7
0    female  north     food        noon      week_2        6             7
21   female  north  leisure     evening      week_3        6             7
95   female  south   beauty     morning      week_4        6             7
138  female   east   beauty       night      week_1        6             7
272    male   east   beauty        noon      week_2        6             7
231    male  south   beauty     evening      week_4        5             7
237    male  south   beauty     morning      week_3       17             8
93   female  south   beauty     morning      week_3       13             8
43   female  north   beauty       night      week_4       12             8
120  female   east  leisure       night      week_2       12             8
162    male  north  leisure        noon      week_1       12             8
22   female  north  leisure     evening      week_1       11             8
204    male  south     food     morning      week_2       11             8
73   female  south  leisure       night      week_3       10             8
86   female  south   beauty     evening      week_1       10             8
12   female  north     food     morning      week_2        9             8
52   female  south     food     evening      week_2        9             8
67   female  south  leisure        noon      week_4        9             8
147    male  north     food        noon      week_4        9             8
172    male  north  leisure     morning      week_2        9             8
268    male   east  leisure     morning      week_2        9             8
98   female   east     food        noon      week_1        8             8
106  female   east     food       night      week_1        8             8
212    male  south  leisure     evening      week_2        8             8
225    male  south   beauty        noon      week_3        8             8
228    male  south   beauty     evening      week_2        8             8
42   female  north   beauty       night      week_1        7             8
57   female  south     food       night      week_3        7             8
102  female   east     food     evening      week_1        7             8
185    male  north   beauty       night      week_3        7             8
221    male  south  leisure     morning      week_3        7             8
122  female   east  leisure       night      week_1        6             8
133  female   east   beauty     evening      week_3        6             8
271    male   east  leisure     morning      week_4        6             8
65   female  south  leisure        noon      week_3        5             8
124  female   east  leisure     morning      week_2        5             8
163    male  north  leisure        noon      week_4        5             8
168    male  north  leisure       night      week_2        5             8
37   female  north   beauty     evening      week_3        4             8
137  female   east   beauty       night      week_3        4             8
55   female  south     food     evening      week_4        3             8
270    male   east  leisure     morning      week_1        3             8
150    male  north     food     evening      week_1       14             9
182    male  north   beauty     evening      week_1       13             9
188    male  north   beauty     morning      week_2       13             9
254    male   east     food     morning      week_1       13             9
24   female  north  leisure       night      week_2       12             9
96   female   east     food        noon      week_2       12             9
240    male   east     food        noon      week_2       12             9
58   female  south     food       night      week_1       11             9
78   female  south  leisure     morning      week_1       11             9
119  female   east  leisure     evening      week_4       11             9
77   female  south  leisure     morning      week_3       10             9
260    male   east  leisure     evening      week_2       10             9
8    female  north     food       night      week_2        9             9
15   female  north     food     morning      week_4        9             9
74   female  south  leisure       night      week_1        9             9
92   female  south   beauty     morning      week_2        8             9
139  female   east   beauty       night      week_4        8             9
267    male   east  leisure       night      week_4        8             9
211    male  south  leisure        noon      week_4        7             9
226    male  south   beauty        noon      week_1        7             9
110  female   east     food     morning      week_1        6             9
112  female   east  leisure        noon      week_2        6             9
199    male  south     food     evening      week_4        6             9
230    male  south   beauty     evening      week_1        6             9
235    male  south   beauty       night      week_4        6             9
245    male   east     food     evening      week_3        6             9
287    male   east   beauty     morning      week_4        6             9
68   female  south  leisure     evening      week_2        5             9
148    male  north     food     evening      week_2        5             9
217    male  south  leisure       night      week_3        5             9
113  female   east  leisure        noon      week_3        4             9
51   female  south     food        noon      week_4        1             9
223    male  south  leisure     morning      week_4       15            10
129  female   east   beauty        noon      week_3       14            10
141  female   east   beauty     morning      week_3       14            10
278    male   east   beauty     evening      week_1       14            10
123  female   east  leisure       night      week_4       13            10
173    male  north  leisure     morning      week_3       12            10
190    male  north   beauty     morning      week_1       11            10
17   female  north  leisure        noon      week_3       10            10
50   female  south     food        noon      week_1       10            10
116  female   east  leisure     evening      week_2       10            10
184    male  north   beauty       night      week_2       10            10
187    male  north   beauty       night      week_4       10            10
36   female  north   beauty     evening      week_2        9            10
59   female  south     food       night      week_4        9            10
64   female  south  leisure        noon      week_2        9            10
109  female   east     food     morning      week_3        9            10
146    male  north     food        noon      week_1        9            10
152    male  north     food       night      week_2        9            10
229    male  south   beauty     evening      week_3        9            10
35   female  north   beauty        noon      week_4        8            10
94   female  south   beauty     morning      week_1        8            10
100  female   east     food     evening      week_2        8            10
165    male  north  leisure     evening      week_3        8            10
192    male  south     food        noon      week_2        8            10
28   female  north  leisure     morning      week_2        7            10
54   female  south     food     evening      week_1        7            10
126  female   east  leisure     morning      week_1        7            10
198    male  south     food     evening      week_1        7            10
7    female  north     food     evening      week_4        6            10
18   female  north  leisure        noon      week_1        6            10
142  female   east   beauty     morning      week_1        6            10
232    male  south   beauty       night      week_2        6            10
32   female  north   beauty        noon      week_2        5            10
143  female   east   beauty     morning      week_4        5            10
284    male   east   beauty     morning      week_2        5            10
216    male  south  leisure       night      week_2        3            10
88   female  south   beauty       night      week_2       11            11
134  female   east   beauty     evening      week_1       11            11
183    male  north   beauty     evening      week_4       11            11
253    male   east     food     morning      week_3       11            11
2    female  north     food        noon      week_1       10            11
171    male  north  leisure       night      week_4       10            11
3    female  north     food        noon      week_4        9            11
34   female  north   beauty        noon      week_1        9            11
121  female   east  leisure       night      week_3        9            11
247    male   east     food     evening      week_4        9            11
111  female   east     food     morning      week_4        8            11
207    male  south     food     morning      week_4        8            11
103  female   east     food     evening      week_4        7            11
169    male  north  leisure       night      week_3        7            11
16   female  north  leisure        noon      week_2        6            11
60   female  south     food     morning      week_2        6            11
85   female  south   beauty     evening      week_3        6            11
130  female   east   beauty        noon      week_1        6            11
71   female  south  leisure     evening      week_4        5            11
5    female  north     food     evening      week_3        4            11
38   female  north   beauty     evening      week_1        4            11
80   female  south   beauty        noon      week_2        4            11
208    male  south  leisure        noon      week_2        4            11
6    female  north     food     evening      week_1        3            11
23   female  north  leisure     evening      week_4       17            12
193    male  south     food        noon      week_3       13            12
140  female   east   beauty     morning      week_2       12            12
189    male  north   beauty     morning      week_3       12            12
248    male   east     food       night      week_2       11            12
158    male  north     food     morning      week_1       10            12
280    male   east   beauty       night      week_2       10            12
145    male  north     food        noon      week_3        8            12
220    male  south  leisure     morning      week_2        8            12
249    male   east     food       night      week_3        8            12
53   female  south     food     evening      week_3        7            12
180    male  north   beauty     evening      week_2        6            12
19   female  north  leisure        noon      week_4        5            12
156    male  north     food     morning      week_2        5            12
246    male   east     food     evening      week_1        5            12

### 3. Scale of the continuous covariates

Nearest neighbor uses a pooled z-score. The mean and standard deviation are taken over both arms together.

In [3]:
from core.matching import covariate_scale

covariate_scale(focal, comparison, spec["numeric"])

                   covariate  pooled_mean   pooled_sd
0                        age    31.990270    7.799631
1           duration_seconds    18.114971    5.978199
2          plays_labeled_14d    10.126177    5.417745
3          plays_labeled_60d    28.145904   14.949883
4        plays_unlabeled_14d    33.976070   18.471131
5        plays_unlabeled_60d    93.824617   51.121309
6     watch_time_labeled_14d    22.833114   12.011098
7     watch_time_labeled_60d    61.166759   32.913057
8   watch_time_unlabeled_14d    62.153965   34.182051
9   watch_time_unlabeled_60d   167.357081   87.441237
10       creator_uploads_14d     3.580979    1.525077
11       creator_uploads_60d     8.892627    3.768850
12         creator_plays_14d    88.274474   35.490417
13         creator_plays_60d   265.396191  111.625171
14    creator_watch_time_14d   160.995067   65.378205
15    creator_watch_time_60d   481.648220  198.350157
16         creator_followers   775.760920  617.645031

### 4. Nearest neighbor inside the cell

Each focal unit takes the comparison unit in the same cell with the smallest Euclidean distance. A caliper, when there is one, sets the distance to infinity and that neighbor is dropped. The ledger counts, per cell, how many focal units were kept and how many were dropped.

In [4]:
from core.matching import match_process

pairs, ledger = match_process(
    focal,
    comparison,
    spec["exact"],
    spec["numeric"],
    spec["outcomes"],
    spec.get("caliper") or {},
)
ledger.sort_values(["n_dropped", "n_focal"], ascending=[False, False])

     gender   city category time_of_day upload_week  n_focal  n_comparison  n_matched  n_dropped  median_distance
105  female   east     food       night      week_3       11             6          5          6         4.386333
160    male  north  leisure        noon      week_2       10             3          4          6         3.946283
11   female  north     food       night      week_4        8             3          2          6         4.744453
62   female  south     food     morning      week_1       12             2          7          5         4.653968
213    male  south  leisure     evening      week_3       12             7          7          5         4.673762
10   female  north     food       night      week_1       11             7          6          5         5.133353
66   female  south  leisure        noon      week_1       11             7          6          5         5.017106
4    female  north     food     evening      week_2        9             5          4          5         4.805458
33   female  north   beauty        noon      week_3       17             4         13          4         5.823283
153    male  north     food       night      week_3       13             5          9          4         5.258459
162    male  north  leisure        noon      week_1       12             8          8          4         5.203661
234    male  south   beauty       night      week_1       12             3          8          4         5.131119
20   female  north  leisure     evening      week_2       11             7          7          4         4.528924
170    male  north  leisure       night      week_1       11             5          7          4         4.780114
206    male  south     food     morning      week_1       11             4          7          4         5.151270
154    male  north     food       night      week_1       10             5          6          4         4.466181
132  female   east   beauty     evening      week_2        9             6          5          4         4.199967
194    male  south     food        noon      week_1        9             7          5          4         5.828381
195    male  south     food        noon      week_4        9             6          5          4         4.770080
201    male  south     food       night      week_3        9             5          5          4         4.269192
255    male   east     food     morning      week_4        9             7          5          4         4.265831
151    male  north     food     evening      week_4        8             3          4          4         4.488024
18   female  north  leisure        noon      week_1        6            10          2          4         4.151352
219    male  south  leisure       night      week_4        6             3          2          4         4.867191
175    male  north  leisure     morning      week_4        5             2          1          4         4.342244
93   female  south   beauty     morning      week_3       13             8         10          3         5.506857
135  female   east   beauty     evening      week_4       13             3         10          3         4.598887
193    male  south     food        noon      week_3       13            12         10          3         4.586722
43   female  north   beauty       night      week_4       12             8          9          3         3.891616
282    male   east   beauty       night      week_1       12             7          9          3         3.992774
49   female  south     food        noon      week_3       11             7          8          3         4.471698
88   female  south   beauty       night      week_2       11            11          8          3         4.296377
204    male  south     food     morning      week_2       11             8          8          3         5.066025
2    female  north     food        noon      week_1       10            11          7          3         3.974146
29   female  north  leisure     morning      week_3       10             6          7          3         4.795457
86   female  south   beauty     evening      week_1       10             8          7          3         4.849065
127  female   east  leisure     morning      week_4       10             7          7          3         5.381994
155    male  north     food       night      week_4       10             6          7          3         5.023123
174    male  north  leisure     morning      week_1       10             4          7          3         5.870465
260    male   east  leisure     evening      week_2       10             9          7          3         3.962926
79   female  south  leisure     morning      week_4        9             5          6          3         5.191329
101  female   east     food     evening      week_3        9             5          6          3         5.351307
196    male  south     food     evening      week_2        9             6          6          3         4.423644
209    male  south  leisure        noon      week_3        9             7          6          3         5.381404
210    male  south  leisure        noon      week_1        8             5          5          3         3.788415
225    male  south   beauty        noon      week_3        8             8          5          3         5.147704
269    male   east  leisure     morning      week_3        8             7          5          3         5.571990
31   female  north  leisure     morning      week_4        7             5          4          3         6.475327
114  female   east  leisure        noon      week_1        7             5          4          3         3.475467
149    male  north     food     evening      week_3        7             6          4          3         4.941182
203    male  south     food       night      week_4        7             5          4          3         4.262818
221    male  south  leisure     morning      week_3        7             8          4          3         4.523591
164    male  north  leisure     evening      week_2        6             4          3          3         4.117383
46   female  north   beauty     morning      week_1        5             4          2          3         4.149948
179    male  north   beauty        noon      week_4        5             3          2          3         5.717827
222    male  south  leisure     morning      week_1        5             4          2          3         6.454381
75   female  south  leisure       night      week_4       17             7         15          2         4.916627
150    male  north     food     evening      week_1       14             9         12          2         5.021086
26   female  north  leisure       night      week_1       11             5          9          2         4.042625
248    male   east     food       night      week_2       11            12          9          2         5.874966
285    male   east   beauty     morning      week_3       11             4          9          2         5.531208
158    male  north     food     morning      week_1       10            12          8          2         5.288888
181    male  north   beauty     evening      week_3       10             5          8          2         4.827321
263    male   east  leisure     evening      week_4       10             7          8          2         5.321584
15   female  north     food     morning      week_4        9             9          7          2         4.577669
36   female  north   beauty     evening      week_2        9            10          7          2         4.796300
52   female  south     food     evening      week_2        9             8          7          2         4.169921
59   female  south     food       night      week_4        9            10          7          2         4.198542
74   female  south  leisure       night      week_1        9             9          7          2         4.688620
121  female   east  leisure       night      week_3        9            11          7          2         4.770376
172    male  north  leisure     morning      week_2        9             8          7          2         4.429928
200    male  south     food       night      week_2        9             7          7          2         4.573637
215    male  south  leisure     evening      week_4        9             5          7          2         6.020445
259    male   east  leisure        noon      week_4        9             7          7          2         4.422790
25   female  north  leisure       night      week_3        8             7          6          2         4.945200
100  female   east     food     evening      week_2        8            10          6          2         5.033218
177    male  north   beauty        noon      week_3        8             6          6          2         4.363711
224    male  south   beauty        noon      week_2        8             6          6          2         4.520230
228    male  south   beauty     evening      week_2        8             8          6          2         5.040352
238    male  south   beauty     morning      week_1        8             7          6          2         5.280765
239    male  south   beauty     morning      week_4        8             7          6          2         5.247932
39   female  north   beauty     evening      week_4        7             4          5          2         4.781273
87   female  south   beauty     evening      week_4        7            13          5          2         3.435871
169    male  north  leisure       night      week_3        7            11          5          2         4.301801
202    male  south     food       night      week_1        7             7          5          2         4.961896
211    male  south  leisure        noon      week_4        7             9          5          2         4.628615
264    male   east  leisure       night      week_2        7             6          5          2         5.352325
89   female  south   beauty       night      week_3        6             4          4          2         4.726223
110  female   east     food     morning      week_1        6             9          4          2         5.341111
117  female   east  leisure     evening      week_3        6             5          4          2         4.479886
180    male  north   beauty     evening      week_2        6            12          4          2         4.241766
235    male  south   beauty       night      week_4        6             9          4          2         4.436626
272    male   east   beauty        noon      week_2        6             7          4          2         4.643426
68   female  south  leisure     evening      week_2        5             9          3          2         5.025070
76   female  south  leisure     morning      week_2        5             6          3          2         4.668431
217    male  south  leisure       night      week_3        5             9          3          2         4.625988
55   female  south     food     evening      week_4        3             8          1          2         4.119345
223    male  south  leisure     morning      week_4       15            10         14          1         4.369587
205    male  south     food     morning      week_3       14            16         13          1         4.624469
278    male   east   beauty     evening      week_1       14            10         13          1         4.343404
123  female   east  leisure       night      week_4       13            10         12          1         4.593651
125  female   east  leisure     morning      week_3       13             7         12          1         5.586147
188    male  north   beauty     morning      week_2       13             9         12          1         4.788889
254    male   east     food     morning      week_1       13             9         12          1         5.162520
24   female  north  leisure       night      week_2       12             9         11          1         5.201619
96   female   east     food        noon      week_2       12             9         11          1         4.042377
108  female   east     food     morning      week_2       12             7         11          1         5.300970
173    male  north  leisure     morning      week_3       12            10         11          1         4.847180
189    male  north   beauty     morning      week_3       12            12         11          1         4.163639
240    male   east     food        noon      week_2       12             9         11          1         4.156640
22   female  north  leisure     evening      week_1       11             8         10          1         5.591867
48   female  south     food        noon      week_2       11             6         10          1         3.537735
58   female  south     food       night      week_1       11             9         10          1         4.947809
107  female   east     food       night      week_4       11             7         10          1         4.587892
119  female   east  leisure     evening      week_4       11             9         10          1         4.690369
134  female   east   beauty     evening      week_1       11            11         10          1         5.147636
178    male  north   beauty        noon      week_1       11             7         10          1         4.030207
190    male  north   beauty     morning      week_1       11            10         10          1         4.330833
261    male   east  leisure     evening      week_3       11             6         10          1         4.599183
41   female  north   beauty       night      week_3       10            13          9          1         4.368390
77   female  south  leisure     morning      week_3       10             9          9          1         3.952591
83   female  south   beauty        noon      week_4       10            13          9          1         4.763954
187    male  north   beauty       night      week_4       10            10          9          1         4.049329
191    male  north   beauty     morning      week_4       10             7          9          1         4.010034
262    male   east  leisure     evening      week_1       10             7          9          1         5.716538
274    male   east   beauty        noon      week_1       10             7          9          1         4.455706
280    male   east   beauty       night      week_2       10            12          9          1         4.505670
1    female  north     food        noon      week_3        9             6          8          1         4.696289
3    female  north     food        noon      week_4        9            11          8          1         4.151904
12   female  north     food     morning      week_2        9             8          8          1         4.977799
56   female  south     food       night      week_2        9             7          8          1         4.642257
64   female  south  leisure        noon      week_2        9            10          8          1         4.184095
67   female  south  leisure        noon      week_4        9             8          8          1         4.492885
97   female   east     food        noon      week_3        9             4          8          1         5.719366
128  female   east   beauty        noon      week_2        9            19          8          1         3.906732
152    male  north     food       night      week_2        9            10          8          1         4.671066
229    male  south   beauty     evening      week_3        9            10          8          1         4.387871
236    male  south   beauty     morning      week_2        9             7          8          1         6.200298
30   female  north  leisure     morning      week_1        8             7          7          1         5.574602
44   female  north   beauty     morning      week_2        8             6          7          1         4.718639
92   female  south   beauty     morning      week_2        8             9          7          1         5.738422
99   female   east     food        noon      week_4        8             7          7          1         4.278904
104  female   east     food       night      week_2        8             7          7          1         4.910044
139  female   east   beauty       night      week_4        8             9          7          1         5.358699
157    male  north     food     morning      week_3        8             6          7          1         4.007264
207    male  south     food     morning      week_4        8            11          7          1         5.159690
220    male  south  leisure     morning      week_2        8            12          7          1         4.449790
241    male   east     food        noon      week_3        8             5          7          1         4.180773
249    male   east     food       night      week_3        8            12          7          1         3.565504
256    male   east  leisure        noon      week_2        8             6          7          1         4.047776
27   female  north  leisure       night      week_4        7             6          6          1         5.188556
42   female  north   beauty       night      week_1        7             8          6          1         4.904095
45   female  north   beauty     morning      week_3        7             6          6          1         5.711478
54   female  south     food     evening      week_1        7            10          6          1         5.112781
57   female  south     food       night      week_3        7             8          6          1         3.761179
61   female  south     food     morning      week_3        7            15          6          1         4.364424
63   female  south     food     morning      week_4        7             4          6          1         3.951359
69   female  south  leisure     evening      week_3        7             7          6          1         5.378618
72   female  south  leisure       night      week_2        7             7          6          1         4.459007
84   female  south   beauty     evening      week_2        7            18          6          1         5.570730
102  female   east     food     evening      week_1        7             8          6          1         5.142754
103  female   east     food     evening      week_4        7            11          6          1         4.727087
185    male  north   beauty       night      week_3        7             8          6          1         4.237208
0    female  north     food        noon      week_2        6             7          5          1         4.728320
122  female   east  leisure       night      week_1        6             8          5          1         4.661999
130  female   east   beauty        noon      week_1        6            11          5          1         4.155008
138  female   east   beauty       night      week_1        6             7          5          1         4.553053
199    male  south     food     evening      week_4        6             9          5          1         3.960962
271    male   east  leisure     morning      week_4        6             8          5          1         4.373393
277    male   east   beauty     evening      week_3        6             5          5          1         4.884335
283    male   east   beauty       night      week_4        6            13          5          1         5.136671
71   female  south  leisure     evening      week_4        5            11          4          1         4.599961
124  female   east  leisure     morning      week_2        5             8          4          1         4.879774
161    male  north  leisure        noon      week_3        5            14          4          1         4.414185

### 5. What was dropped, and how often a comparison unit is reused

Replacement means one comparison unit may be the neighbor for more than one focal unit.

In [5]:
import pandas as pd

reuse = pairs["comparison_row"].value_counts()
pd.DataFrame([{
    "focal_units": len(focal),
    "comparison_units": len(comparison),
    "exact_cells": len(ledger),
    "dropped_no_comparison_in_cell": int(ledger.loc[ledger["n_comparison"] == 0, "n_focal"].sum()),
    "dropped_by_caliper_or_empty_neighborhood": int(ledger.loc[ledger["n_comparison"] > 0, "n_dropped"].sum()),
    "pairs": len(pairs),
    "comparison_units_used": int(reuse.shape[0]),
    "max_reuse": int(reuse.max()) if len(reuse) else 0,
}])

   focal_units  comparison_units  exact_cells  dropped_no_comparison_in_cell  dropped_by_caliper_or_empty_neighborhood  pairs  comparison_units_used  max_reuse
0         2400              2400          288                              0                                       372   2028                   1210          8

### 6. Eight pairs

Exact covariates are copied onto both sides. They agree by construction. `distance` is the z-score Euclidean distance of the chosen neighbor.

In [6]:
show = ["distance"]
for column in spec["exact"]:
    show += [f"{column}_focal", f"{column}_comparison"]
for column in spec.get("caliper") or {}:
    gap = f"{column}_gap"
    pairs[gap] = (pairs[f"{column}_focal"] - pairs[f"{column}_comparison"]).abs()
    show.append(gap)
pairs[show].head(8)

   distance gender_focal gender_comparison city_focal city_comparison category_focal category_comparison time_of_day_focal time_of_day_comparison upload_week_focal upload_week_comparison  duration_seconds_gap
0  6.183805       female            female      north           north           food                food              noon                   noon            week_2                 week_2              1.845844
1  4.641880       female            female      north           north           food                food              noon                   noon            week_2                 week_2              2.216721
2  4.728320       female            female      north           north           food                food              noon                   noon            week_2                 week_2              2.777206
3  7.511530       female            female      north           north           food                food              noon                   noon            week_2                 week_2              0.827548
4  4.094523       female            female      north           north           food                food              noon                   noon            week_2                 week_2              2.700354
5  5.781511       female            female      north           north           food                food              noon                   noon            week_3                 week_3              2.684250
6  5.867640       female            female      north           north           food                food              noon                   noon            week_3                 week_3              0.384740
7  9.242077       female            female      north           north           food                food              noon                   noon            week_3                 week_3              1.566490

### 7. Balance before and after

Standardized mean difference of each covariate, on the raw arms and on the matched pairs.

In [7]:
from core.balance import balance_before_after

balance = balance_before_after(focal, comparison, pairs, list(spec["exact"]) + list(spec["numeric"]))
balance

                   covariate  mean_focal_before  mean_comparison_before  standardized_difference_before  mean_focal_after  mean_comparison_after  standardized_difference_after
0                        age          31.943388               32.037152                       -0.012019         31.905186              32.050861                      -0.019377
1          creator_followers         774.913916              776.607925                       -0.002742        775.094217             730.507639                       0.076896
2          creator_plays_14d          88.422992               88.125955                        0.008368         88.586933              85.877726                       0.079442
3          creator_plays_60d         264.844269              265.948113                       -0.009887        265.498269             261.316058                       0.038991
4        creator_uploads_14d           3.629452                3.532505                        0.063588          3.615120               3.497372                       0.079605
5        creator_uploads_60d           8.861475                8.923779                       -0.016528          8.866177               8.633352                       0.066321
6     creator_watch_time_14d         161.123644              160.866490                        0.003933        162.030311             157.900206                       0.065661
7     creator_watch_time_60d         486.042350              477.254091                        0.044308        487.297661             463.137222                       0.128073
8           duration_seconds          18.104832               18.125109                       -0.003391         18.059137              18.071530                      -0.002455
9          plays_labeled_14d          10.132037               10.120318                        0.002163         10.078492               9.779537                       0.059415
10         plays_labeled_60d          28.278028               28.013779                        0.017673         28.395380              27.551151                       0.058352
11       plays_unlabeled_14d          34.258274               33.693867                        0.030553         34.435702              32.730874                       0.095329
12       plays_unlabeled_60d          94.219730               93.429505                        0.015455         94.764172              91.124253                       0.075716
13    watch_time_labeled_14d          22.917924               22.748305                        0.014119         22.915384              21.914831                       0.087087
14    watch_time_labeled_60d          60.643810               61.689708                       -0.031775         60.451039              59.002436                       0.047422
15  watch_time_unlabeled_14d          61.892911               62.415019                       -0.015272         61.547639              60.098335                       0.045277
16  watch_time_unlabeled_60d         165.955706              168.758457                       -0.032050        166.403569             161.672588                       0.057759

### 8. The contrast

Mean of focal minus comparison. The standard error is Abadie-Imbens, with up to five within-arm neighbors. The Hodges-Lehmann median and the Wilcoxon p-value are the rank summary beside that mean.

In [8]:
from core.imbens import contrast_table

effects = contrast_table(
    focal,
    comparison,
    pairs,
    spec["outcomes"],
    spec["exact"],
    spec["numeric"],
    n_neighbors=int(cfg.get("imbens_neighbors", 5)),
)
out = root / "data" / "results"
out.mkdir(parents=True, exist_ok=True)
pairs.to_csv(out / "consumer_pairs.csv", index=False)
effects.to_csv(out / "consumer_effects.csv", index=False)
balance.to_csv(out / "consumer_balance.csv", index=False)
effects

           outcome  n_pairs  hl_focal_minus_comparison  mean_difference  wilcoxon_statistic     wilcoxon_p  variance  standard_error  z_statistic  p_value  ci95_low  ci95_high
0  early_retention     2028                  -0.029416        -0.029208            478484.0   1.176856e-96  0.000003        0.001654   -17.655664      0.0 -0.032450  -0.025966
1  valid_view_rate     2028                  -0.057839        -0.058086            154650.0  7.628523e-241  0.000003        0.001707   -34.022055      0.0 -0.061433  -0.054740
2   full_view_rate     2028                  -0.023088        -0.022978            449275.0  5.592157e-107  0.000001        0.001175   -19.555744      0.0 -0.025281  -0.020675
3    view_fraction     2028                  -0.042747        -0.042540            393926.0  5.342872e-128  0.000004        0.002005   -21.216307      0.0 -0.046470  -0.038610